config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/favorites', to: 'static_pages#favorites'

  get '/signup', to: 'users#new' 
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do 
    member do
      patch :unban
      patch :ban
      resources :chatrooms
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :posts do 
    member do
      post :add_to_favorites
      delete :remove_from_favorites
    end
    collection do
      get :filter
    end
  end

  resources :car_evaluations, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :user_favorite_cars, dependent: :destroy
  has_many :favorites, through: :user_favorite_cars, source: :post
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :ban, :unban]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:ban, :unban]

  def index
    @users = User.where(activated: true).order(:name).paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
  end

  def ban
    User.find(params[:id]).update(banned: true)
    flash[:success] = "User banned!"
    redirect_to users_url
  end

  def unban
    User.find(params[:id]).update(banned: false)
    flash[:success] = "User unbanned!"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/edit.html.haml
- provide(:title, "Edit user")
%h1 Update your profile
.row
  .col-md-6.col-md-offset-3
    = form_with(model: @user, local: true) do |f|
      = render 'shared/error_messages', object: f.object

      = f.label :name
      = f.text_field :name, class: 'form-control'

      = f.label :email
      = f.email_field :email, class: 'form-control'

      = f.label :password
      = f.password_field :password, class: 'form-control'

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'

      = f.submit "Save changes", class: "btn btn-primary"

    .gravatar_edit
      = gravatar_for @user

      %a{href: "https://gravatar.com/emails", target: "_blank"} change

app/views/users/index.html.haml
- provide(:title, 'All users')
%h1 All users

= will_paginate

%ul.users
  - @users.each do |user|
    %li
      = gravatar_for user, size: 50
      = link_to user.name, user
      - if current_user.admin? && !current_user?(user)
        |
        - if user.banned?
          = link_to "unban", unban_user_path(user), method: :patch ,confirm: "Are you sureyou want to unban #{user.name}?", style: "color: green;"
        -else
          = link_to "ban", ban_user_path(user), method: :patch, confirm: "Are you sureyou want to ban #{user.name}?", style: "color: red;"

= will_paginate

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up
.row
  .col-md-6.col-md-offset-3
    = form_for(@user, url: signup_path, local: true) do |f|
      = render 'shared/error_messages', object: f.object

      = f.label :name
      = f.text_field :name, class: "form-control", autocomplete: "off", required: true

      = f.label :email
      = f.email_field :email, class: "form-control", autocomplete: "off", required: true

      = f.label :password
      = f.password_field :password, class: "form-control", autocomplete: "off", required: true

      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: "form-control", autocomplete: "off", required: true

      = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.haml
= provide :title, @user.name
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        %br
        = @user.name
        = @user.email
  .col-md-8
    - if @user.posts.any?
      %h3= "Cars for sale: #{@user.posts.count}"
      %ol.posts
        = render @posts
      = will_paginate @posts