config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/favorites', to: 'static_pages#favorites'

  get '/signup', to: 'users#new' 
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do 
    member do
      patch :unban
      patch :ban
      resources :chatrooms
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :posts do 
    member do
      post :add_to_favorites
      delete :remove_from_favorites
    end
    collection do
      get :filter
    end
  end

  resources :car_evaluations, only: [:new, :create]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :user_favorite_cars, dependent: :destroy
  has_many :favorite_users, through: :user_favorite_cars, source: :user
  has_many_attached :images  
  default_scope -> { order(created_at: :desc) }
  before_save :capitalize_fields
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 2, maximum: 50 }
  validates :content, length: { maximum: 140 }
  validates :images, content_type: { in: ['image/jpg', 'image/jpeg', 'image/png'], message: "must be a valid image format" }, 
                     size: { less_than: 5.megabytes, message: "should be less than 5MB" }

  def capitalize_fields
    self.title = title.capitalize
    self.brand = brand.capitalize
    self.model = model.capitalize
    self.location = location.capitalize
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_image(image, size = 400)
    image.variant(resize_to_limit: [size, size])
  end

  def resize_to_fill(image, w = 425, h = 250)
    image.variant(resize_to_fill: [w, h])
  end

end

app/views/posts/_post.html.haml
%li{ id: "post#{post.id}" }
  = link_to gravatar_for(post.user, size: 50), post.user
  %span 
    %h4.post-title= link_to post.title, post_path(post)
  .car-items
    .car-info
      - if post.images.attached?
        .content= link_to image_tag(resize_to_fill(post.images.first)), post_path(post)
      - else
        .content= link_to image_tag("car-default.png", style: "width: 425px; height: 250px; cursor:pointer;"), post_path(post)
    .car-info
      .content= "Brand: #{post.brand}"
      .content= "Model: #{post.model}"
      .content= "Year: #{post.year}"
      .content= "Km: #{post.mileage}"
      .content= "Fuel: #{post.fuel}"
      .content= "Gearbox: #{post.gearbox}"
      .content= "Transmition: #{post.transmition}"
      .content= "CC: #{post.cc}"
      .content= "HP: #{post.power}"
      .content= "Price: #{post.price}€"
      .content= "Posted #{time_ago_in_words(post.created_at)} ago."
      .content
        - if logged_in?
          - if current_user?(post.user) || current_user.admin?
            = link_to raw("<i class='fas fa-edit'></i> <span> Edit </span>"), edit_post_path(post)
            = " | "
            = link_to raw("<i class='fa fa-trash' aria-hidden='true'></i> <span> Delete </span>"), post ,method: :delete, data: { confirm: "You sure?" }
          - else
            %span
            - if !current_user.favorites.include?(post)
              = link_to raw("<i class='far fa-star'></i> <span> Add to Favorites </span>"), add_to_favorites_post_path(post), method: :post, remote: true, class: "add-post-#{post.id}", onclick: "addToFavorites(#{post.id})"
              = link_to raw("<i class='fa fa-star favorite'></i> <span> Remove from Favorites </span>"), remove_from_favorites_post_path(post), method: :delete, remote: true, class: "remove-post-#{post.id} hidden", onclick: "removeFromFavorites(#{post.id})"
            - else
              = link_to raw("<i class='far fa-star'></i> <span> Add to Favorites </span>"), add_to_favorites_post_path(post), method: :post, remote: true, class: "add-post-#{post.id} hidden", onclick: "addToFavorites(#{post.id})"
              = link_to raw("<i class='fa fa-star favorite'></i> <span> Remove from Favorites </span>"), remove_from_favorites_post_path(post), method: :delete, remote: true, class: "remove-post-#{post.id}", onclick: "removeFromFavorites(#{post.id})"

:javascript
  function addToFavorites(id) {
    $(".remove-post-" + id).removeClass("hidden")
    $(".add-post-" + id).addClass("hidden")
  }

  function removeFromFavorites(id) {
    $(".remove-post-" + id).addClass("hidden")
    $(".add-post-" + id).removeClass("hidden")
  }

app/views/posts/edit.html.haml
= provide(:title, "Edit #{@post.title}")

%h1 Edit Post
%br

= form_with(model: @post, method: :put, local: true) do |f|
  = render 'shared/error_messages', object: @post
  = f.label :title
  %span.filter= f.text_field :title, class: "form-control", autocomplete: "off", required: true
  %br
  .form_fileds 
    .form_field
      = f.label :location
      %span.filter= f.text_field :location, class: "form-control", autocomplete: "off"
    .form_field
      = f.label :body
      %span.filter= f.select :body, options_for_select(@body_type, @post.body), {}, class: "form-control big-form"
    .form_field
      = f.label :brand
      %span.filter= f.select :brand, options_for_select(@brand, @post.brand), {}, {class: "form-control big-form", id: "brand-select", required: true}
    .form_field
      = f.label :model
      %span.filter= f.select :model, options_for_select(@model[:"#{@post.brand}"], @post.model), {}, {class: "form-control big-form", id: "model-select", required: true}
    .form_field
      = f.label :year
      %span.filter= f.number_field :year, class: "form-control", autocomplete: "off", required: true
    .form_field
      = f.label :km
      %span.filter= f.number_field :mileage, class: "form-control", autocomplete: "off", required: true
    .form_field
      = f.label :fuel_type
      %span.filter= f.select :fuel, options_for_select(@fuel_type, @post.fuel), {}, class: "form-control big-form"
    .form_field
      = f.label "Engine Displacement (cc)"
      %span.filter= f.number_field :cc, class: "form-control", autocomplete: "off", required: true
    .form_field
      = f.label :horsepower
      %span.filter= f.number_field :power, class: "form-control", autocomplete: "off", required: true
    .form_field
      = f.label :transmition_type
      %span.filter= f.select :transmition, options_for_select(@transmition_type, @post.transmition), {}, class: "form-control big-form"
    .form_field
      = f.label :gearbox_type
      %span.filter= f.select :gearbox, options_for_select(@gearbox_type, @post.gearbox), {}, class: "form-control big-form"
    .form_field
      = f.label "Price(€)"
      %span.filter= f.number_field :price, class: "form-control", autocomplete: "off", required: true
  %br
  = f.label :descritpion
  .field 
    %span.filter= f.text_area :content, placeholder: "Add description...", class: "form-control", autocomplete: "off"

  .images
    - (0..9).each do |i|
      .image
        - img = "add-photo.png"
        - img = @post.images[i] if @post.images[i].present?
        - field_value = ""
        - field_value = @post.images[i] if @post.images[i].present?
        = image_tag(img, id: "image-#{i}", onclick: "addPhoto(#{i})", style: "width: 200px; height: 200px; cursor:pointer;")
        = f.file_field "images[#{i}]", multiple: false, accept: "image/jpeg,image/gif,image/png", class: "post_images", style: "display:none", id: "post-images-#{i}", onchange:"readURL(this, #{i})"
  %br
  = f.submit "Edit Post", class: "btn btn-primary"

:javascript
  $(".post_images").bind("change", function() {
    const size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#post_image").val("");
    }
  });

  function addPhoto(i) {
    $("#post-images-" + i).trigger('click')
  }

  function readURL(input, i) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('#image-' + i)
          .attr('src', e.target.result)
          .maxidth(200)
          .height(200);
      };

      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#brand-select").on("change", function(){
    var brand = this.value
    $("#model-select").empty()
    if (brand == "") {
      $("#model-select").prop( "disabled", true )
    } else {
      $("#model-select").prop( "disabled", false )
      $("#model-select").append($('<option>', {
                    value: "",
                    text: ""
                }));
      $.each(gon.model[brand].sort(), function( index , value){
        $("#model-select").append($('<option>', {
                    value: value,
                    text: value
                }));
      })
    }
  })

app/views/posts/filter.html.haml
= provide(:title, "Home")

.row
  %aside.col-md-3
    - if logged_in?
      %section.user_info
        = render 'shared/user_info'
    %section.user_info
      = render 'shared/filters'
  .col-md-9
    = render 'shared/feed'  
    
    

app/views/posts/filter.js.haml
$("ol.posts").empty()
$("div.pagination").empty()
- if @feed_items.any?
  $("ol.posts").append("#{ j render @feed_items}")
  $("div.pagination").html("#{ j will_paginate @feed_items }")

app/views/posts/new.html.haml
= provide(:title, "New Post")

%h1 New Post

%br

= form_with(model: @post, method: :post, local: true) do |f|
  = render 'shared/error_messages', object: @post
  = f.label :title
  %span.filter= f.text_field :title, class: "form-control", autocomplete: "off", required: true
  %br
  .form_fileds 
    .form_field
      = f.label :location
      %span.filter= f.text_field :location, class: "form-control", autocomplete: "off"
    .form_field
      = f.label :body
      %span.filter= f.select :body, options_for_select(@body_type), {include_blank: true}, {class: "form-control big-form", required: true}
    .form_field
      = f.label :brand
      %span.filter= f.select :brand, options_for_select(@brand), {include_blank: true}, {class: "form-control big-form", id: "brand-select", required: true}
    .form_field
      = f.label :model
      %span.filter= f.select :model, [], {}, {class: "form-control big-form", id: "model-select", disabled: true, required: true}
    .form_field
      = f.label :year
      %span.filter= f.number_field :year, class: "form-control", autocomplete: "off", required: true
    .form_field
      = f.label :km
      %span.filter= f.number_field :mileage, class: "form-control", autocomplete: "off", required: true
    .form_field
      = f.label :fuel_type
      %span.filter= f.select :fuel, options_for_select(@fuel_type), {include_blank: true}, {class: "form-control big-form", required: true}
    .form_field
      = f.label "Engine Displacement (cc)"
      %span.filter= f.number_field :cc, class: "form-control", autocomplete: "off", required: true
    .form_field
      = f.label :horsepower
      %span.filter= f.number_field :power, class: "form-control", autocomplete: "off", required: true
    .form_field
      = f.label :transmition_type
      %span.filter= f.select :transmition, options_for_select(@transmition_type), {include_blank: true}, {class: "form-control big-form", required: true }
    .form_field
      = f.label :gearbox_type
      %span.filter= f.select :gearbox, options_for_select(@gearbox_type), {include_blank: true}, {class: "form-control big-form", required: true}
    .form_field
      = f.label "Price(€)"
      %span.filter= f.number_field :price, class: "form-control", autocomplete: "off", required: true
  %br
  = f.label :descritpion
  .field 
    %span.filter= f.text_area :content, placeholder: "Add description...", class: "form-control", autocomplete: "off"
  .images
    - (1..10).each do |i|
      .image
        = image_tag("add-photo.png", id: "image-#{i}", onclick: "addPhoto(#{i})", style: "width: 200px; height: 200px; cursor:pointer;")
        = f.file_field "images[#{i}]", multiple: false, accept: "image/jpeg,image/gif,image/png", class: "post_images", style: "display:none", id: "post-images-#{i}", onchange:"readURL(this, #{i})"
  
  = f.submit "Add Post", class: "btn btn-primary"

:javascript
  $(".post_images").bind("change", function() {
    const size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#post_image").val("");
    }
  });

  function addPhoto(i) {
    $("#post-images-" + i).trigger('click')
  }

  function readURL(input, i) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('#image-' + i)
          .attr('src', e.target.result)
      };

      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#brand-select").on("change", function(){
    var brand = this.value
    $("#model-select").empty()
    if (brand == "") {
      $("#model-select").prop( "disabled", true )
    } else {
      $("#model-select").prop( "disabled", false )
      $("#model-select").append($('<option>', {
                    value: "",
                    text: ""
                }));
      $.each(gon.model[brand].sort(), function( index , value){
        $("#model-select").append($('<option>', {
                    value: value,
                    text: value
                }));
      })
    }
  })

app/views/posts/show.html.haml
= provide(:title, @post.title)

.row
  %aside.col-md-3
    %section.user_info
      %h1
        = link_to gravatar_for(@post.user), @post.user
        %br
        = @post.user.name
        = @post.user.email
  .col-md-9
    %span.post_title
      %h2= @post.title
      %br
    - if @post.images.attached?
      .slideshow-container
        - @post.images.each_with_index do |p, i| 
          .mySlides
            .numbertext= "#{i + 1}/#{@post.images.size}"
            = image_tag(resize_to_fill(p,850, 500))
        %a.prev.prev_photo{:onclick => "plusSlides(-1)"} ❮
        %a.next.next_photo{:onclick => "plusSlides(1)"} ❯
      %br
      %div{ style: "text-align:center"}
        - @post.images.each_with_index do |p, i| 
          %span.dot{onclick: "currentSlide(#{i + 1})"}
    .posts
      %h4.content= "Price: #{@post.price}€"
      %h4.content= "Year: #{@post.year}"
      %h4.content= "Location: #{@post.location || '-' }"
      .specs 
        %h4.spec.content= "Body: #{@post.body}"
        %h4.spec.content= "Brand: #{@post.brand}"
        %h4.spec.content= "Model: #{@post.model || '-' }"
        %h4.spec.content= "KM: #{@post.mileage}"
        %h4.spec.content= "Fuel: #{@post.fuel}"
        %h4.spec.content= "Engine Displacement (cc): #{@post.cc}"
        %h4.spec.content= "Horsepower: #{@post.power}"
        %h4.spec.content= "Gearbox: #{@post.gearbox}"
        %h4.spec.content= "Transmition: #{@post.transmition}"
      %br
      %h4.content{ style: "white-space: pre-line;"}= @post.content
      %br
      - if current_user.present?
        - if current_user?(@post.user) || current_user.admin?
          .content
            = link_to raw("<i class='fas fa-edit'></i> <span> Edit </span>"), edit_post_path(@post)
            = " | "
            = link_to raw("<i class='fa fa-trash' aria-hidden='true'></i> <span> Delete </span>"), @post ,method: :delete, data: { confirm: "You sure?" }
:javascript
  var slideIndex = 1;
  showSlides(slideIndex);

  // Next/previous controls
  function plusSlides(n) {
    showSlides(slideIndex += n);
  }

  // Thumbnail image controls
  function currentSlide(n) {
    showSlides(slideIndex = n);
  }

  function showSlides(n) {
    let i;
    let slides = document.getElementsByClassName("mySlides");
    let dots = document.getElementsByClassName("dot");
    if (n > slides.length) {slideIndex = 1}
    if (n < 1) {slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
  }