config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/favorites', to: 'static_pages#favorites'

  get '/signup', to: 'users#new' 
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do 
    member do
      patch :unban
      patch :ban
      resources :chatrooms
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :posts do 
    member do
      post :add_to_favorites
      delete :remove_from_favorites
    end
    collection do
      get :filter
    end
  end

  resources :car_evaluations, only: [:new, :create]
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    =  "Autorulate by" 
    = link_to 'Andrei Manaila', 'https://www.linkedin.com/in/andrei-manaila/', target: :_blank
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li= link_to "Help", help_path

app/views/layouts/_header.html.haml
%header{class: "navbar navbar-fixed-top navbar-inverse"}
  .container
    = link_to "autorulate", root_path, id: "logo"
    %nav
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      %ul#bs-example-navbar-collapse-1.nav.navbar-nav.navbar-right.collapse.navbar-collapse
        %li= link_to "Evaluate Car", new_car_evaluation_path
        - if logged_in?
          - if current_user.admin
            %li= link_to "Users", users_path
          - else
            %li= link_to "New Post", new_post_path
            %li= link_to "Messages", chatrooms_path(current_user)
            %li= link_to "Favorites", favorites_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li= link_to "Log out", logout_path, method: :delete
        - else
          %li= link_to "Log in", login_path
          %li= link_to "Sign up", signup_path

app/views/layouts/application.html.haml
%html
  %head
    %title= "Autorulate | " + yield(:title)
    %meta{ charset: "utf-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = Gon::Base.render_data
    %link{:href => "https://use.fontawesome.com/releases/v5.0.6/css/all.css", :rel => "stylesheet"}
    = favicon_link_tag asset_path('deal.png')
  %body
    = render partial: "layouts/header"
    .container
      - flash.each do |message_type, message|
        %div{ class: "alert alert-#{message_type}" }
          = message
      = yield
      = render partial: "layouts/footer"